// Production console in real Chromium; only a finite typed Host boundary is injected.
// No lab Host, serial/SDK transport, outputs or hardware are reachable.
import assert from 'node:assert/strict';
import {createServer} from 'node:http';
import {readFile,mkdir} from 'node:fs/promises';
import {fileURLToPath,pathToFileURL} from 'node:url';
import {resolve,sep} from 'node:path';
const root=resolve(fileURLToPath(new URL('../../..',import.meta.url)));
const {chromium}=await import(pathToFileURL(process.env.YANG_LAB_PLAYWRIGHT_MODULE).href);
const html=`<!doctype html><link rel="stylesheet" href="/App/web/style.css">
<div class="app-shell"><aside class="sidebar"><nav id="navigation"></nav><span id="sidebar-mode"></span><span id="sidebar-subtitle"></span></aside><div class="main-shell"><header class="topbar"><span id="current-page-title"></span><span id="session-pill"></span></header><div id="background-work" hidden></div><main id="content" class="content"></main></div></div><div id="notice" hidden></div>
<script type="module">
import {mountConsole} from '/App/web/console-ui.js';import {createConsoleSession} from '/App/web/main.js';
const h='a'.repeat(32),b='b'.repeat(32),d='c'.repeat(32),s='d'.repeat(32),domain={kind:'device',id:d},key=h+'/device/'+d,context={session_id:'f'.repeat(32),connection_id:'e'.repeat(32),epoch:1,domain};
location.hash='#/host/'+h+'/device/'+d;const mode=new URL(location.href).searchParams.get('mode')||'normal';
// Rust serde_json::Value orders object keys. The wire contract does not preserve JS insertion order.
const wire=value=>JSON.parse(JSON.stringify(value,(_key,item)=>item&&typeof item==='object'&&!Array.isArray(item)?Object.fromEntries(Object.entries(item).sort(([a],[b])=>a.localeCompare(b))):item));
if(mode==='sorted-connect'){context.connection_id=null;context.epoch=0;}
const fields=Object.fromEntries(Object.entries({temperature_c:25,target_c:25,tec_enabled:true,current_ma:3,current_enabled:mode==='unknown-off'}).map(([name,value])=>[name,{value,connection_id:context.connection_id,revision:1,quality:'fresh',observed_age_s:0}]));
const device={state:mode==='unknown-off'?'ACTIVE':'READY',connected:true,fields,pid:null,current_operation:null,resource:'COM4'};
const lease={token:'1'.repeat(32),boot_id:b,session_id:s,domain,control_epoch:0,expires_in_ms:10000};
const state={host_id:h,host_name:'Finite Gain UI fixture',mode:'real',registry:{registry_rev:1,settings:{},devices:[{device_id:d,name:'Gain chip',model_id:'gain',profile_id:'cp210x-serial',params:{port:'COM4'},config_rev:1}],drafts:[],setups:[]},control:{['device:'+d]:{state:'CONTROLLED',controller_session:s,control_epoch:0}},domains:{['device:'+d]:{state:device.state,context,device,host_sample_ms:0,active_request_id:null,pending_request_id:null,safety_request_id:null,readback_request_id:null}}};
if(mode==='sorted-connect'){state.domains['device:'+d].device=null;state.domains['device:'+d].state='DISCONNECTED';}
let subscriber,ui,seq=0,sequence=0,budget=0,revision=1,pendingId,safetyId,finishOff,finishResume,finishApply;const calls=[],operations=new Map();
function publish(){if(++budget>250)throw Error('Finite publication budget exceeded');state.domains['device:'+d].host_sample_ms=performance.now();subscriber({type:'snapshot',host_id:h,boot_id:b,seq:++seq,data:wire(state)});}
function terminal(id,phase='completed',error=null){return wire({request_id:id,operation_id:id,domain,status:'Terminal',phase,result:{context:structuredClone(context),result:{},error:error?{message:error}:null}});}
function sample(value,quality='fresh',age=0){revision++;for(const field of Object.values(fields)){field.revision=revision;field.observed_age_s=age;field.quality=quality;}fields.temperature_c.value=value;publish();}
async function delayApply(id,name){const selected={set_current:'delayed-set-current',ramp_current:'delayed-ramp',set_pid:'delayed-pid'};if(mode!==selected[name])return;state.domains['device:'+d].active_request_id=id;publish();await new Promise(resolve=>finishApply=resolve);finishApply=null;state.domains['device:'+d].active_request_id=null;}
function finishStart(){if(!pendingId)throw Error('No pending start');fields.current_enabled.value=true;fields.current_ma.value=42;device.state='ACTIVE';state.domains['device:'+d].state='ACTIVE';device.current_operation={...device.current_operation,phase:'completed',active:false,current_ma:42,steps_completed:39,steps_total:39};state.domains['device:'+d].active_request_id=null;operations.set(pendingId,terminal(pendingId));sample(25);}
function finishSafety(){if(!safetyId)throw Error('No uncertain safety');fields.current_enabled.value=false;context.epoch++;device.state='READY';state.domains['device:'+d].state='STOP_HELD';operations.set(safetyId,terminal(safetyId));sample(25);}
const client={preferences:async()=>({}),connect:async()=>({connected:true,mode:'real',worker_protocol:3}),disconnect:async()=>{},catalog:async()=>({categories:['Custom'],models:[{id:'gain',name:'Gain Chip Driver',profiles:[{id:'cp210x-serial',open_effects:['DTR_RTS_reset_not_verified']}]}]}),subscribe:async fn=>{subscriber=fn;return()=>{};},requestSnapshot:async()=>{publish();return{seq};},ping:async()=>({monotonic_ms:performance.now(),client_session_id:s,boot_id:b}),remoteStatus:async()=>({peers:[],pending:[]}),renew:async()=>({...lease}),nextSequence:()=>++sequence,
 prepare:async intent=>{if(intent.lease_token!==lease.token||intent.control_epoch!==0||JSON.stringify(wire(intent.context))!==JSON.stringify(wire(context))||intent.config_rev!==1)throw Error('Incorrect authority/context');calls.push({stage:'prepare',name:intent.method==='action'?intent.params.name:intent.method,epoch:intent.context.epoch});return{token:'proof'};},
 execute:async(id,intent)=>{if(intent.confirmation!=='proof')throw Error('Non-typed action');const {name,args}=intent.params;
  if(intent.method==='connect'){if(context.connection_id!==null||intent.params.acknowledge_lifecycle!==true)throw Error('Unexpected connect');calls.push({stage:'execute',name:'connect',id});context.connection_id='e'.repeat(32);context.epoch=1;for(const field of Object.values(fields))field.connection_id=context.connection_id;fields.current_enabled.value=false;fields.tec_enabled.value=false;state.domains['device:'+d].device=device;state.domains['device:'+d].state='READY';const record=terminal(id);operations.set(id,record);sample(25);return record;}
  if(intent.method==='resume'){calls.push({stage:'execute',name:'resume',args:intent.params,id});if(state.domains['device:'+d].state!=='STOP_HELD'||intent.params.confirm!==true)throw Error('Unverified held resume');
   if(mode==='unknown-resume'){const unknown={request_id:id,operation_id:id,domain,status:'Outcome Unknown',phase:'timed_out_unknown',result:null};operations.set(id,unknown);return unknown;}
   state.domains['device:'+d].state='READY';const record=terminal(id);operations.set(id,record);publish();if(mode==='delayed-resume')await new Promise(resolve=>finishResume=resolve);return record;}
  if(intent.method!=='action')throw Error('Unexpected method');calls.push({stage:'execute',name,args,id});
  if(name==='read_pid'){device.pid={values:[.35,.1,0],connection_id:context.connection_id,revision:1,observed_age_s:0,quality:'fresh',error:null};}
  else if(name==='set_pid'){if(JSON.stringify(args)!==JSON.stringify({p:.5,i:.2,d:0}))throw Error('Unexpected PID args');await delayApply(id,name);device.pid={...device.pid,values:[args.p,args.i,args.d],revision:device.pid.revision+1};}
  else if(name==='set_temperature'){if(args.temperature_c!==26.5)throw Error('Unexpected temperature');fields.target_c.value=args.temperature_c;}
  else if(name==='enable_tec'){fields.tec_enabled.value=true;}
  else if(name==='start_current'){if(JSON.stringify(args)!==JSON.stringify({current_ma:42,soft_start:true,step_ma:1,interval_s:.1,timeout_s:30}))throw Error('Unexpected start args');pendingId=id;state.domains['device:'+d].active_request_id=id;device.current_operation={kind:name,phase:'waiting_stable',active:true,target_ma:42,current_ma:3,steps_completed:0,steps_total:39,elapsed_s:0,error:null};const accepted={request_id:id,operation_id:id,domain,status:'Accepted',phase:'running',result:null};operations.set(id,accepted);publish();if(mode==='unknown-start')throw Object.assign(Error('Start admission reply unavailable'),{code:'OutcomeUnknown'});return accepted;}
  else if(name==='set_current'){if(JSON.stringify(args)!==JSON.stringify({current_ma:42}))throw Error('Unexpected current args');await delayApply(id,name);fields.current_ma.value=42;}
  else if(name==='ramp_current'){if(JSON.stringify(args)!==JSON.stringify({current_ma:50,step_ma:1,interval_s:.1}))throw Error('Unexpected ramp args');await delayApply(id,name);fields.current_ma.value=50;}
  else if(name==='disable_current'||name==='disable_tec'){
   if(mode==='unknown-off'){safetyId=id;operations.set(id,{request_id:id,operation_id:id,domain,status:'Outcome Unknown',phase:'timed_out_unknown',result:null});throw Object.assign(Error('Shutdown reply lost'),{outcomeUnknown:true});}
   if(mode==='delayed-off'&&name==='disable_current')await new Promise(resolve=>finishOff=resolve);
   context.epoch++;fields.current_enabled.value=false;if(name==='disable_tec')fields.tec_enabled.value=false;device.state='READY';state.domains['device:'+d].state='STOP_HELD';state.domains['device:'+d].active_request_id=null;
   state.domains['device:'+d].safety={state:'STOP_HELD',phase:'completed',context:structuredClone(context),attempt_id:id,error:null,result:{attempt_id:id,effective_intent:name==='disable_current'?'current_off':'tec_off'}};
   if(pendingId&&operations.get(pendingId)?.status==='Accepted'){const canceled=terminal(pendingId,'failed_after_call_started','Canceled');canceled.result.error.type='Canceled';operations.set(pendingId,canceled);device.current_operation={...device.current_operation,phase:'canceled',active:false,error:'Canceled'};}
  }else throw Error('Unexpected Gain action '+name);
  const record=terminal(id);operations.set(id,record);sample(fields.temperature_c.value);return record;},
 operation:async id=>{calls.push({stage:'query',id});if(!operations.has(id))throw Error('Unknown original request');return operations.get(id);}};
const session=createConsoleSession(client,()=>ui?.requestRender());ui=mountConsole(session,{event:{listen(){}}});await ui.ready;session.store.setLease(key,lease);ui.render();
window.fixture={ready:true,publish,sample,finishStart,finishSafety,finishApply(){if(!finishApply)throw Error('No delayed Apply');finishApply();},finishOff(){if(!finishOff)throw Error('No delayed Off');finishOff();},finishResume(){if(!finishResume)throw Error('No delayed resume');finishResume();},calls,device,state,ui,context,offline(){session.offline(h);},reconnect(){sample(25.7);},boot(){subscriber({type:'snapshot',host_id:h,boot_id:'9'.repeat(32),seq:++seq,data:state});},replace(){context.connection_id='7'.repeat(32);context.epoch++;for(const field of Object.values(fields))field.connection_id=context.connection_id;device.pid=null;sample(26);}};
</script>`;
const server=createServer(async(req,res)=>{try{const pathname=new URL(req.url,'http://localhost').pathname;if(pathname==='/'){res.setHeader('Content-Type','text/html');res.end(html);return;}const path=resolve(root,'.'+pathname);if(!path.startsWith(resolve(root,'App/web')+sep)){res.writeHead(404).end();return;}res.setHeader('Content-Type',path.endsWith('.js')?'text/javascript':'text/css');res.end(await readFile(path));}catch{res.writeHead(404).end();}});
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));let browser;
const output=resolve(root,'Result/gain-redesign/browser');await mkdir(output,{recursive:true});
try{
 browser=await chromium.launch({executablePath:process.env.YANG_LAB_BROWSER,headless:true,timeout:15000});
 async function open(mode='normal'){const page=await browser.newPage({viewport:{width:1440,height:1050}}),errors=[];page.setDefaultTimeout(12000);page.on('pageerror',error=>errors.push(error.message));await page.goto('http://127.0.0.1:'+server.address().port+'/?mode='+mode);await page.waitForFunction(()=>window.fixture?.ready);if(mode!=='sorted-connect')await page.waitForFunction(()=>document.getElementById('gain-pid-p')?.value==='0.35');return {page,errors};}
 async function fill(page,id,value){const input=page.locator('#'+id);await input.focus();await input.fill(value);}
 async function clickDigit(page,id,position){const input=page.locator('#'+id);await page.getByRole('heading',{name:'Overall status',exact:true}).click();const point=await input.evaluate((e,index)=>{const css=getComputedStyle(e),ctx=document.createElement('canvas').getContext('2d');ctx.font=css.font;const advance=ctx.measureText('0').width+(parseFloat(css.letterSpacing)||0);return{x:e.clientLeft+parseFloat(css.paddingLeft)+(index+.75)*advance-e.scrollLeft,y:e.clientHeight/2};},position);await input.click({position:point});assert.deepEqual(await input.evaluate(e=>[e.selectionStart,e.selectionEnd]),[position,position+1],id+' first pointer click selects digit '+position);}
 const digit=await open();const digitPage=digit.page;
 for(const [id,initial,whole]of [['gain-temp','25.000','2'],['gain-current','003.000','3']]){const input=digitPage.locator('#'+id);assert.equal(await input.getAttribute('type'),'text',id+' uses a selectable fixed digit editor');assert.equal(await input.getAttribute('inputmode'),'decimal');assert.equal(await input.getAttribute('data-digits'),'3');assert.equal(await input.getAttribute('data-whole'),whole);assert.equal(await input.inputValue(),initial);for(const position of [...initial].map((char,index)=>/\d/.test(char)?index:null).filter(index=>index!==null))await clickDigit(digitPage,id,position);}
 const digitBefore=await digitPage.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length),digitTemp=digitPage.locator('#gain-temp'),digitCurrent=digitPage.locator('#gain-current');
 await fill(digitPage,'gain-temp','25.999');await clickDigit(digitPage,'gain-temp',5);await digitTemp.press('ArrowUp');assert.equal(await digitTemp.inputValue(),'26.000','fractional carry advances the whole value');await digitTemp.press('ArrowLeft');await digitTemp.press('ArrowLeft');await digitTemp.press('ArrowLeft');assert.deepEqual(await digitTemp.evaluate(e=>[e.selectionStart,e.selectionEnd]),[1,2],'left crosses the decimal separator');await digitTemp.press('ArrowRight');assert.deepEqual(await digitTemp.evaluate(e=>[e.selectionStart,e.selectionEnd]),[3,4],'right skips the decimal separator');await digitTemp.press('5');assert.equal(await digitTemp.inputValue(),'26.500');assert.deepEqual(await digitTemp.evaluate(e=>[e.selectionStart,e.selectionEnd]),[4,5],'digit replacement advances to the next slot');
 await clickDigit(digitPage,'gain-current',1);await digitCurrent.press('4');await digitCurrent.press('2');assert.equal(await digitCurrent.inputValue(),'042.000');assert.deepEqual(await digitCurrent.evaluate(e=>[e.selectionStart,e.selectionEnd]),[4,5],'replacement advances across the current decimal separator');
 await digitCurrent.dispatchEvent('keydown',{key:'ArrowUp',isComposing:true});assert.equal(await digitCurrent.inputValue(),'042.000','IME composition arrows do not edit the numeric draft');
 const selected=await digitCurrent.evaluate(e=>[e.selectionStart,e.selectionEnd]);await digitPage.evaluate(async()=>{for(let i=0;i<5;i++){await new Promise(resolve=>setTimeout(resolve,200));fixture.sample(25+i/100);}});assert.equal(await digitCurrent.inputValue(),'042.000');assert.deepEqual(await digitCurrent.evaluate(e=>[e.selectionStart,e.selectionEnd]),selected);assert.equal(await digitPage.evaluate(()=>document.activeElement.id),'gain-current');
 await digitPage.locator('#navigation a[href="#overview"]').click();await digitCurrent.waitFor({state:'hidden'});await digitPage.evaluate(()=>{fixture.sample(25.1);location.hash='#/host/'+'a'.repeat(32)+'/device/'+'c'.repeat(32);});await digitCurrent.waitFor();assert.equal(await digitCurrent.inputValue(),'042.000','keyboard-only current draft survives navigation');assert.equal(await digitTemp.inputValue(),'26.500','keyboard-only temperature draft survives navigation');assert.equal(await digitPage.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length),digitBefore,'pointer, arrows, replacement, telemetry and navigation remain local');
 await digitTemp.press('Enter');await digitPage.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='set_temperature'));await digitPage.locator('[data-op="gain-set-current"]').click();await digitPage.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='set_current'));assert.deepEqual(await digitPage.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name!=='read_pid').map(c=>[c.name,c.args])),[['set_temperature',{temperature_c:26.5}],['set_current',{current_ma:42}]]);await digitPage.screenshot({path:resolve(output,'fixed-digit-targets.png'),fullPage:true});assert.deepEqual(digit.errors,[]);await digitPage.close();console.log('PASS: Gain fixed digit targets select the first clicked slot, carry, skip decimals, advance replacement, retain keyboard drafts at 5 Hz/navigation and write only on Enter/Apply.');
 const arrows=await open();await clickDigit(arrows.page,'gain-temp',1);await arrows.page.locator('#gain-temp').press('ArrowUp');await clickDigit(arrows.page,'gain-current',2);await arrows.page.locator('#gain-current').press('ArrowUp');await arrows.page.evaluate(()=>fixture.sample(25.1));assert.equal(await arrows.page.locator('#gain-temp').inputValue(),'26.000','arrow-only temperature changes are dirty drafts');assert.equal(await arrows.page.locator('#gain-current').inputValue(),'004.000','arrow-only current changes are dirty drafts');
 await arrows.page.locator('[data-op="gain-disable-current"]').click();await arrows.page.waitForFunction(()=>fixture.context.epoch===2&&fixture.state.domains['device:'+'c'.repeat(32)].state==='STOP_HELD');await arrows.page.evaluate(()=>fixture.sample(25.2));assert.equal(await arrows.page.locator('#gain-temp').inputValue(),'26.000','Off epoch preserves the temperature draft');assert.equal(await arrows.page.locator('#gain-current').inputValue(),'004.000','Off epoch preserves the current draft');assert.deepEqual(await arrows.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').map(c=>c.name)),['read_pid','disable_current'],'Off cannot flush or replay draft values');
 await arrows.page.evaluate(()=>fixture.replace());await arrows.page.waitForFunction(()=>document.getElementById('gain-current')?.value==='003.000');assert.equal(await arrows.page.locator('#gain-temp').inputValue(),'25.000','a replacement connection discards the previous connection draft');assert.equal(await arrows.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&['set_current','set_temperature','start_current'].includes(c.name)).length),0);assert.deepEqual(arrows.errors,[]);await arrows.page.close();console.log('PASS: arrow-only dirty Gain drafts survive telemetry and Off epoch, and connection replacement invalidates them without a wire write.');
 const bounds=await open();await fill(bounds.page,'gain-temp','15');assert.equal(await bounds.page.locator('#gain-temp').inputValue(),'15','pasted text remains raw while editing');await clickDigit(bounds.page,'gain-temp',5);assert.equal(await bounds.page.locator('#gain-temp').inputValue(),'15.000','blur normalizes pasted text before digit selection');await bounds.page.locator('#gain-temp').press('ArrowDown');assert.equal(await bounds.page.locator('#gain-temp').inputValue(),'15.000','temperature lower limit rejects the next digit step');await fill(bounds.page,'gain-current','200');await clickDigit(bounds.page,'gain-current',6);await bounds.page.locator('#gain-current').press('ArrowUp');assert.equal(await bounds.page.locator('#gain-current').inputValue(),'200.000','current upper limit rejects the next digit step');assert.equal(await bounds.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length),1,'bounds validation never writes');assert.deepEqual(bounds.errors,[]);await bounds.page.close();console.log('PASS: raw paste normalizes on blur and fixed digit editing preserves Gain operating bounds without writing.');
 const precision=await open();for(const [id,value,formatted,op,name,arg]of [['gain-temp','26.5004','26.500','gain-set-temp','set_temperature','temperature_c'],['gain-current','42.0004','042.000','gain-set-current','set_current','current_ma']]){await fill(precision.page,id,value);assert.equal(await precision.page.locator('#'+id).inputValue(),value);await precision.page.locator('#'+id).press('Enter');assert.equal(await precision.page.locator('#'+id).inputValue(),formatted,'Enter normalizes pasted extra precision before submitting');await precision.page.waitForFunction(action=>fixture.calls.some(c=>c.stage==='execute'&&c.name===action),name);await precision.page.waitForFunction(button=>!document.querySelector('[data-op="'+button+'"]').disabled,op);await fill(precision.page,id,value);await precision.page.locator('[data-op="'+op+'"]').click();await precision.page.waitForFunction(action=>fixture.calls.filter(c=>c.stage==='execute'&&c.name===action).length===2,name);assert.deepEqual(await precision.page.evaluate(action=>fixture.calls.filter(c=>c.stage==='execute'&&c.name===action).map(c=>c.args),name),Array.from({length:2},()=>({[arg]:Number(formatted)})),id+' Enter and Apply normalize the same three decimal target');}assert.deepEqual(precision.errors,[]);await precision.page.close();console.log('PASS: pasted extra precision normalizes identically for Gain Enter and Apply.');
 const canonical=await open('sorted-connect');await canonical.page.locator('[data-op="connect"]').click();await canonical.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='connect')&&(document.querySelector('[data-ui="query-original"]')||fixture.calls.some(c=>c.stage==='execute'&&c.name==='read_pid')));
 console.log('Canonical Host connect observation:',await canonical.page.evaluate(()=>({state:fixture.state.domains['device:'+'c'.repeat(32)].state,connection:fixture.context.connection_id,pidReads:fixture.calls.filter(c=>c.stage==='execute'&&c.name==='read_pid').length,notice:document.querySelector('#notice').textContent,uncertain:Boolean(document.querySelector('[data-ui="query-original"]'))})));
 assert.equal(await canonical.page.locator('[data-ui="query-original"]').count(),0,'a successful canonical Host connect must not be classified uncertain');await canonical.page.waitForFunction(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='read_pid').length===1);await canonical.page.waitForFunction(()=>document.getElementById('gain-pid-p')?.value==='0.35');assert.equal(await canonical.page.locator('.instance-connection').textContent(),'ConnectedDisconnect');assert.deepEqual(canonical.errors,[]);await canonical.page.close();console.log('PASS: canonical Rust Host JSON Connect completes once and triggers one PID read without false uncertainty.');
 // This finite stream verifies browser projection; real Host publication is covered by native Host tests.
 const fiveHz=await open();await fiveHz.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-current"]').disabled);await fiveHz.page.locator('#gain-current').fill('42');await fiveHz.page.locator('#gain-current').focus();
 const initialPoints=Number(await fiveHz.page.locator('[data-trend="gain-temperature"]').getAttribute('data-observations'));
 const observations=await fiveHz.page.evaluate(async()=>{const samples=[];for(let i=0;i<15;i++){await new Promise(resolve=>setTimeout(resolve,200));const atMs=performance.now();fixture.sample(25+i/100);samples.push({atMs,revision:fixture.device.fields.temperature_c.revision});fixture.publish();}return samples;});
 await fiveHz.page.waitForFunction(count=>Number(document.querySelector('[data-trend="gain-temperature"]').dataset.observations)===count,initialPoints+15);
 const projected=await fiveHz.page.locator('.gain-trend-measured').last().getAttribute('points'),xs=projected.trim().split(/\s+/).slice(-15).map(point=>Number(point.split(',')[0]));
 assert.equal(new Set(observations.map(sample=>sample.revision)).size,15);assert.equal(xs.length,15);assert.ok(xs.every((x,i)=>i===0||x>xs[i-1]),'every received revision retains its distinct observation time');
 assert.ok(Math.abs(xs.at(-1)-xs[0]-560*(observations.at(-1).atMs-observations[0].atMs)/300000)<.1,'trend spacing follows actual source time instead of revision indexes');
 const projectedCount=await fiveHz.page.locator('[data-trend="gain-temperature"]').getAttribute('data-observations');await fiveHz.page.evaluate(()=>{fixture.publish();fixture.ui.render();fixture.ui.render();});assert.equal(await fiveHz.page.locator('[data-trend="gain-temperature"]').getAttribute('data-observations'),projectedCount,'interleaved heartbeats and repaints never add thermal observations');
 assert.equal(await fiveHz.page.locator('#gain-current').inputValue(),'42');assert.equal(await fiveHz.page.evaluate(()=>document.activeElement.id),'gain-current');assert.equal(await fiveHz.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length),1,'live telemetry preserves the draft without instrument actions');assert.deepEqual(fiveHz.errors,[]);await fiveHz.page.close();console.log('PASS: finite 5 Hz Host observations retain every revision and actual time spacing, skip heartbeats, and preserve focused drafts.');
 const tab=await open();await tab.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-current"]').disabled);await tab.page.locator('#gain-temp').fill('26.5');await tab.page.locator('#gain-current').fill('42');const tabBefore=await tab.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length);await tab.page.locator('#gain-temp').focus();await tab.page.locator('#gain-temp').press('Tab');
 console.log('Target Tab observation:',await tab.page.evaluate(()=>({id:document.activeElement.id,op:document.activeElement.dataset.op||null,text:document.activeElement.textContent})));
 assert.equal(await tab.page.evaluate(()=>document.activeElement.id),'gain-current','Tab from Target Temperature must focus Target Current');await tab.page.locator('#gain-current').press('Tab');assert.equal(await tab.page.evaluate(()=>document.activeElement.id),'gain-temp','Tab from Target Current must cycle back to Target Temperature');await tab.page.locator('#gain-temp').press('Shift+Tab');assert.equal(await tab.page.evaluate(()=>document.activeElement.id),'gain-current','Shift+Tab reverses the target-field cycle');await tab.page.locator('#gain-current').press('Shift+Tab');assert.equal(await tab.page.evaluate(()=>document.activeElement.id),'gain-temp');
 assert.equal(await tab.page.locator('#gain-temp').inputValue(),'26.500');assert.equal(await tab.page.locator('#gain-current').inputValue(),'042.000');assert.equal(await tab.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length),tabBefore,'focus changes do not submit any command');await tab.page.screenshot({path:resolve(output,'control-panels-keyboard.png'),fullPage:true});assert.deepEqual(tab.errors,[]);await tab.page.close();console.log('PASS: Tab and Shift+Tab cycle both target fields, normalize drafts on blur and issue no command.');
 const offEnter=await open('delayed-set-current');await offEnter.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-current"]').disabled);await offEnter.page.locator('#gain-pid-details > summary').click();const editBefore=await offEnter.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length);
 for(const [id,value]of [['gain-temp','26.5'],['gain-current','42'],['gain-pid-p','0.5'],['gain-pid-i','0.2'],['gain-pid-d','0']]){const field=offEnter.page.locator('#'+id);await field.fill(value);await field.press('ArrowUp');await field.press('ArrowDown');assert.equal(Number(await field.inputValue()),Number(value));}
 for(const id of ['gain-temp','gain-current','gain-pid-p']){const field=offEnter.page.locator('#'+id);for(const key of ['Control+Enter','Alt+Enter','Meta+Enter'])await field.press(key);await field.dispatchEvent('keydown',{key:'Enter',repeat:true});await field.dispatchEvent('keydown',{key:'Enter',isComposing:true});await field.focus();await field.dispatchEvent('keydown',{key:'Tab',isComposing:true});assert.equal(await offEnter.page.evaluate(()=>document.activeElement.id),id,'composing Tab leaves the editing field focused');}
 await offEnter.page.locator('#gain-current').evaluate(field=>field.addEventListener('keydown',event=>event.preventDefault(),{once:true}));await offEnter.page.locator('#gain-current').press('Enter');assert.equal(await offEnter.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length),editBefore,'editing, arrows, modified/repeated/composing/prevented keys cannot write');
 await offEnter.page.locator('#gain-current').focus();await offEnter.page.keyboard.down('Enter');await offEnter.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='set_current'));await offEnter.page.keyboard.down('Enter');await offEnter.page.keyboard.up('Enter');await offEnter.page.locator('#gain-current').press('Enter');await offEnter.page.locator('#gain-temp').press('Enter');
 assert.equal(await offEnter.page.locator('[data-op="gain-set-current"]').isDisabled(),true);assert.equal(await offEnter.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='set_current').length),1,'repeated and pending Enter cannot submit twice');assert.equal(await offEnter.page.evaluate(()=>fixture.device.fields.current_enabled.value),false);await offEnter.page.locator('#gain-current').fill('43');await offEnter.page.evaluate(()=>fixture.finishApply());await offEnter.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-current"]').disabled);
 assert.equal(await offEnter.page.locator('#gain-current').inputValue(),'43','pending edits remain drafts after the captured 42 mA completes');assert.deepEqual(await offEnter.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').map(c=>[c.name,c.args])),[['read_pid',{}],['set_current',{current_ma:42}]]);assert.deepEqual(offEnter.errors,[]);await offEnter.page.close();console.log('PASS: current Off Enter submits set_current once; edits/arrows/modified/composing/repeated/pending keys do not write or replay.');
 const pidEnter=await open('delayed-pid');await pidEnter.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-pid"]').disabled);await pidEnter.page.locator('#gain-pid-details > summary').click();for(const [id,value]of [['gain-pid-p','0.5'],['gain-pid-i','0.2'],['gain-pid-d','0']])await pidEnter.page.locator('#'+id).fill(value);
 for(const [index,id]of ['gain-pid-p','gain-pid-i','gain-pid-d'].entries()){await pidEnter.page.locator('#'+id).press('Enter');await pidEnter.page.waitForFunction(count=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='set_pid').length===count,index+1);await pidEnter.page.locator('#'+id).press('Enter');assert.equal(await pidEnter.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='set_pid').length),index+1);await pidEnter.page.evaluate(()=>fixture.finishApply());await pidEnter.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-pid"]').disabled);}
 assert.deepEqual(await pidEnter.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='set_pid').map(c=>c.args)),Array.from({length:3},()=>({p:.5,i:.2,d:0})));assert.deepEqual(pidEnter.errors,[]);await pidEnter.page.close();console.log('PASS: Enter in each PID coefficient submits one typed set_pid and pending Enter never duplicates it.');
 const first=await open();const page=first.page;await page.waitForFunction(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='read_pid').length===1);
 assert.equal(await page.locator('#gain-pid-p').inputValue(),'0.35');
 await page.locator('#gain-pid-details > summary').click();
 for(const [id,value]of [['gain-temp','26.5'],['gain-current','42'],['gain-pid-p','0.5'],['gain-pid-i','0.2'],['gain-pid-d','0']])await page.locator('#'+id).fill(value);
 const target=page.locator('#gain-temp');await target.focus();const initial=await page.evaluate(()=>({id:document.activeElement.id,scroll:document.querySelector('#content').scrollTop}));
 await page.evaluate(()=>{fixture.sample(25.1);fixture.sample(25.2);fixture.sample(25.3);});await page.waitForFunction(()=>document.querySelector('[data-gain-field="temperature_c"]')?.textContent.includes('25.3'));
 assert.equal(await target.inputValue(),'26.500');assert.equal(await page.locator('#gain-pid-p').inputValue(),'0.5');assert.equal(await page.evaluate(()=>document.activeElement.id),initial.id);
 assert.equal(await page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length),1,'editing and telemetry cannot write');
 await target.press('Enter');await page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='set_temperature'));
 await page.locator('[data-op="gain-set-pid"]').click();await page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='set_pid'));
 assert.equal(await page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='set_temperature').length),1);
 await page.locator('[data-op="gain-enable-current"]').click();await page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='start_current'));
 await page.locator('.gain-operation').waitFor();
 assert.match(await page.locator('#content').textContent(),/Waiting.*stabl|Stabiliz/i);assert.equal(await page.locator('[data-op="gain-disable-current"]').isEnabled(),true);
 await page.locator('#gain-current').fill('50');await page.locator('#navigation a[href="#overview"]').click();await page.locator('#background-work').waitFor({state:'visible'});assert.equal(await page.locator('#background-work').isVisible(),true);
 await page.evaluate(()=>{fixture.sample(25.4);fixture.sample(25.5);location.hash='#/host/'+'a'.repeat(32)+'/device/'+'c'.repeat(32);});await page.locator('#gain-current').waitFor();
 assert.equal(await page.locator('#gain-current').inputValue(),'050.000');await page.screenshot({path:resolve(output,'waiting-stability.png')});assert.deepEqual(first.errors,[]);await page.close();
 console.log('PASS: one initial PID read, draft/focus preservation, no edit writes, Enter/click and visible delayed native start.');
 const navigation=await open();await navigation.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='read_pid'));
 const before=Number(await navigation.page.locator('[data-trend="gain-temperature"]').getAttribute('data-observations'));await navigation.page.locator('#gain-current').fill('42');await navigation.page.locator('#navigation a[href="#overview"]').click();
 await navigation.page.locator('#gain-current').waitFor({state:'hidden'});
 await navigation.page.evaluate(()=>fixture.sample(25.2));await navigation.page.evaluate(()=>{fixture.sample(25.4);location.hash='#/host/'+'a'.repeat(32)+'/device/'+'c'.repeat(32);});await navigation.page.locator('#gain-current').waitFor();
 assert.equal(await navigation.page.locator('#gain-current').inputValue(),'042.000');assert.equal(Number(await navigation.page.locator('[data-trend="gain-temperature"]').getAttribute('data-observations')),before+2);
 const count=await navigation.page.locator('[data-trend="gain-temperature"]').getAttribute('data-observations');await navigation.page.evaluate(()=>{fixture.publish();fixture.ui.render();fixture.ui.render();});assert.equal(await navigation.page.locator('[data-trend="gain-temperature"]').getAttribute('data-observations'),count);
 await navigation.page.evaluate(()=>fixture.sample(25.5,'stale',7));await navigation.page.waitForFunction(()=>document.querySelector('[data-op="gain-set-current"]').disabled);await navigation.page.evaluate(()=>fixture.sample(25.6));await navigation.page.waitForFunction(()=>document.querySelectorAll('.gain-trend-measured').length>=2);
 const segments=await navigation.page.locator('.gain-trend-measured').count();await navigation.page.evaluate(()=>fixture.offline());await navigation.page.waitForFunction(()=>document.querySelector('[data-op="gain-set-current"]').disabled);await navigation.page.evaluate(()=>fixture.reconnect());await navigation.page.waitForFunction(before=>document.querySelectorAll('.gain-trend-measured').length>before,segments);
 await navigation.page.screenshot({path:resolve(output,'rolling-gap-drafts.png')});assert.deepEqual(navigation.errors,[]);await navigation.page.close();console.log('PASS: background history, no heartbeat phantom samples, explicit time gaps and drafts across navigation.');
 const canceled=await open();await canceled.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='read_pid'));await canceled.page.locator('#gain-current').fill('42');await canceled.page.locator('[data-op="gain-enable-current"]').click();await canceled.page.waitForFunction(()=>fixture.device.current_operation?.active);
 await canceled.page.locator('[data-op="gain-disable-current"]').click();await canceled.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='disable_current'));await canceled.page.waitForFunction(()=>fixture.device.current_operation?.phase==='canceled');
 assert.equal(await canceled.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='start_current').length),1);assert.equal(await canceled.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='disable_current').length),1);
 await canceled.page.waitForFunction(()=>document.querySelector('[data-op="gain-enable-current"]')?.disabled===false);assert.equal(await canceled.page.locator('#gain-current').inputValue(),'042.000');assert.equal(await canceled.page.locator('#notice').isVisible(),false,'explicit Off cancellation is not a failure toast');await canceled.page.screenshot({path:resolve(output,'start-canceled-off.png')});
 await canceled.page.locator('[data-op="gain-enable-current"]').click();await canceled.page.waitForFunction(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='start_current').length===2);assert.equal(await canceled.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='resume').length),1);await canceled.page.evaluate(()=>fixture.finishStart());await canceled.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-current"]').disabled);
 await canceled.page.locator('[data-op="gain-disable-tec"]').click();await canceled.page.waitForFunction(()=>fixture.state.domains['device:'+'c'.repeat(32)].state==='STOP_HELD'&&fixture.device.fields.tec_enabled.value===false);await canceled.page.waitForFunction(()=>!document.querySelector('[data-op="gain-enable-tec"]').disabled);await canceled.page.locator('[data-op="gain-enable-tec"]').click();await canceled.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='enable_tec'));
 assert.equal(await canceled.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='resume').length),2);await canceled.page.waitForFunction(()=>document.querySelector('[data-op="gain-enable-current"]')?.disabled===false);await canceled.page.locator('[data-op="gain-enable-current"]').click();await canceled.page.waitForFunction(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='start_current').length===3);assert.equal(await canceled.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='resume').length),2);assert.deepEqual(canceled.errors,[]);await canceled.page.close();console.log('PASS: Off cancels delayed start once; subsequent On resumes verified held metadata once, and TEC Off→On→Current On preserves the draft.');
 const active=await open('delayed-ramp');await active.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='read_pid'));await active.page.locator('#gain-current').fill('42');await active.page.locator('[data-op="gain-enable-current"]').click();await active.page.waitForFunction(()=>fixture.device.current_operation?.active);await active.page.evaluate(()=>fixture.finishStart());await active.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-current"]').disabled);
 await active.page.locator('#gain-current').fill('50');await active.page.locator('#gain-current').press('Enter');await active.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='ramp_current'));await active.page.locator('#gain-current').press('Enter');assert.equal(await active.page.locator('[data-op="gain-set-current"]').isDisabled(),true);assert.equal(await active.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='ramp_current').length),1);await active.page.evaluate(()=>fixture.finishApply());await active.page.waitForFunction(()=>!document.querySelector('[data-op="gain-set-current"]').disabled);assert.equal(await active.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='start_current').length),1);assert.equal(await active.page.evaluate(()=>fixture.device.fields.current_ma.value),50);assert.deepEqual(active.errors,[]);await active.page.close();console.log('PASS: current On Enter uses one native Smooth change ramp without re-enabling output or duplicating pending Enter.');
 const unknown=await open('unknown-off');await unknown.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='read_pid'));await unknown.page.locator('[data-op="gain-disable-current"]').click();await unknown.page.locator('#notice').filter({hasText:'Shutdown reply lost'}).waitFor({state:'visible'});
 await unknown.page.locator('[data-op="gain-disable-current"]').click();await unknown.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='query'));assert.equal(await unknown.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='disable_current').length),1);assert.equal(await unknown.page.locator('[data-op="gain-set-current"]').isDisabled(),true);
 await unknown.page.evaluate(()=>fixture.finishSafety());await unknown.page.locator('[data-ui="query-gain-safety"]').click();await unknown.page.waitForFunction(()=>!document.querySelector('[data-ui="query-gain-safety"]'));assert.deepEqual(unknown.errors,[]);await unknown.page.close();console.log('PASS: uncertain Off keeps normal controls blocked and repeated click only queries the original attempt.');
 const resumeUnknown=await open('unknown-resume');await resumeUnknown.page.locator('[data-op="gain-disable-tec"]').click();await resumeUnknown.page.waitForFunction(()=>document.querySelector('[data-op="gain-enable-tec"]')?.disabled===false);await resumeUnknown.page.locator('[data-op="gain-enable-tec"]').click();await resumeUnknown.page.locator('[data-ui="query-original"]').waitFor();assert.equal(await resumeUnknown.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='enable_tec').length),0);assert.equal(await resumeUnknown.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='resume').length),1);assert.equal(await resumeUnknown.page.locator('[data-op="gain-enable-tec"]').isDisabled(),true);assert.deepEqual(resumeUnknown.errors,[]);await resumeUnknown.page.close();console.log('PASS: unknown metadata resume preserves original identity and sends no captured output action.');
 const startUnknown=await open('unknown-start');await startUnknown.page.locator('#gain-current').fill('42');await startUnknown.page.locator('[data-op="gain-enable-current"]').click();await startUnknown.page.locator('[data-ui="query-original"]').waitFor();const unknownBefore=await startUnknown.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length);await startUnknown.page.locator('#gain-current').press('Enter');await startUnknown.page.locator('#gain-temp').press('Enter');await startUnknown.page.locator('[data-ui="query-original"]').click();await startUnknown.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='query'));assert.equal(await startUnknown.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute').length),unknownBefore,'unknown-disabled Enter cannot submit any normal command');assert.equal(await startUnknown.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='start_current').length),1);assert.equal(await startUnknown.page.locator('[data-op="gain-set-current"]').isDisabled(),true);assert.equal(await startUnknown.page.locator('[data-op="gain-disable-current"]').isEnabled(),true);assert.deepEqual(startUnknown.errors,[]);await startUnknown.page.close();console.log('PASS: typed OutcomeUnknown startup uses original status query, blocks all target Enter writes/replay and retains Off authority.');
 const queued=await open('delayed-off');await queued.page.locator('#gain-current').fill('42');await queued.page.locator('[data-op="gain-enable-current"]').click();await queued.page.waitForFunction(()=>fixture.device.current_operation?.active);await queued.page.locator('[data-op="gain-disable-current"]').click();await queued.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='disable_current'));
 await queued.page.locator('[data-op="gain-disable-tec"]').click();assert.equal(await queued.page.locator('[data-op="gain-disable-tec"]').isDisabled(),true,'the queued intent is visibly busy');assert.equal(await queued.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='disable_tec').length),0,'TEC Off waits for confirmed current shutdown');await queued.page.evaluate(()=>fixture.finishOff());await queued.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='disable_tec'));await queued.page.waitForFunction(()=>fixture.device.current_operation?.phase==='canceled'&&fixture.device.fields.tec_enabled.value===false);
 assert.deepEqual(await queued.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='prepare'&&c.name.startsWith('disable_')).map(c=>[c.name,c.epoch])),[['disable_current',1],['disable_tec',2]]);assert.equal(await queued.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='disable_tec').length),1);assert.equal(await queued.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='start_current').length),1);assert.deepEqual(queued.errors,[]);await queued.page.close();console.log('PASS: stronger TEC Off queues behind delayed Current Off once with the freshly confirmed epoch.');
 const interrupted=await open('delayed-resume');await interrupted.page.locator('[data-op="gain-disable-tec"]').click();await interrupted.page.waitForFunction(()=>document.querySelector('[data-op="gain-enable-tec"]')?.disabled===false);await interrupted.page.locator('[data-op="gain-enable-tec"]').click();await interrupted.page.waitForFunction(()=>fixture.calls.some(c=>c.stage==='execute'&&c.name==='resume'));await interrupted.page.locator('[data-op="gain-disable-current"]').click();await interrupted.page.waitForFunction(()=>fixture.context.epoch===3);await interrupted.page.evaluate(()=>fixture.finishResume());await interrupted.page.locator('#notice').filter({hasText:'No output action was sent'}).waitFor({state:'visible'});
 assert.equal(await interrupted.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='resume').length),1);assert.equal(await interrupted.page.evaluate(()=>fixture.calls.filter(c=>c.stage==='execute'&&c.name==='enable_tec').length),0);assert.equal(await interrupted.page.evaluate(()=>fixture.device.fields.tec_enabled.value),false);assert.deepEqual(interrupted.errors,[]);await interrupted.page.close();console.log('PASS: Off remains usable during delayed metadata resume and its new epoch fences the captured On action.');
}finally{await browser?.close();server.closeAllConnections();await new Promise(resolve=>server.close(resolve));}
