use yang_lab_tlb::*;
use std::{collections::BTreeMap,sync::{Arc,Mutex}};
#[derive(Default)]
struct State { commands:Vec<(String,String)>,opens:usize,closes:usize,close_error:bool,replies:BTreeMap<String,String> }
struct Script(Arc<Mutex<State>>);
impl Wire for Script {
 fn open(&mut self)->Result<Vec<String>> { self.0.lock().unwrap().opens+=1; Ok(vec!["6700 SN1012".into(),"6700 SN1013".into()]) }
 fn query(&mut self,key:&str,command:&str)->Result<String> { let mut s=self.0.lock().unwrap();s.commands.push((key.into(),command.into()));if command=="*IDN?" { return Ok(format!("New_Focus 6700 v2.4 03/19/14 SN{}",key.strip_prefix("6700 SN").unwrap())); } if let Some(v)=s.replies.get(command){return Ok(v.clone())} if command.contains(' '){return Ok("OK".into())} panic!("Unreviewed query {command}") }
 fn close(&mut self)->Result<()> {let mut s=self.0.lock().unwrap();s.closes+=1;if s.close_error{Err(Error{kind:"connection",message:"retained close".into()})}else{Ok(())}}
}
fn fixture(head:&str)->(Bus<Script>,Arc<Mutex<State>>) {let s=Arc::new(Mutex::new(State::default()));s.lock().unwrap().replies=[("SYST:LAS:MODEL?",head),("SYST:LAS:SN?","P1001"),("OUTP:STAT?","0"),("OUTP:TRAC?","1"),("SYST:MCONT?","LOC"),("SOUR:CPOW?","0"),("SENS:WAVE","1060.01"),("SOUR:WAVE?","1060"),("SENS:POW:DIODE","0"),("SOUR:POW:DIODE?","10"),("SENS:CURR:DIODE","0"),("SOUR:CURR:DIODE?","20"),("SOUR:VOLT:PIEZ?","50"),("*OPC?","1"),("*STB?","0")].into_iter().map(|(k,v)|(k.into(),v.into())).collect();(Bus::new(Script(s.clone())),s)}
#[test] fn preserving_identity_and_status(){let(mut b,s)=fixture("6722-P");let id=b.connect("6700 SN1012").unwrap();assert_eq!(id.serial,"1012");assert_eq!(id.head_model,"6722-P");let st=b.status("6700 SN1012").unwrap();assert_eq!(st.wavelength_nm,1060.01);assert!(!st.output_enabled);b.disconnect("6700 SN1012").unwrap();assert!(b.resources_released());assert!(s.lock().unwrap().commands.iter().all(|(_,c)|!c.contains(' ')));}
#[test] fn shared_bus_duplicate_and_scan_preserve_other_session(){let(mut b,s)=fixture("TLB-6721");b.connect("6700 SN1012").unwrap();assert!(b.connect("6700 SN1012").is_err());b.connect("6700 SN1013").unwrap();assert!(b.enumerate().is_err());b.disconnect("6700 SN1012").unwrap();assert_eq!(s.lock().unwrap().closes,0);assert!(b.status("6700 SN1013").is_ok());b.disconnect("6700 SN1013").unwrap();assert_eq!(s.lock().unwrap().closes,1);assert_eq!(s.lock().unwrap().opens,1);}
#[test] fn failed_last_close_retains_and_can_be_retried(){let(mut b,s)=fixture("6722-P");b.connect("6700 SN1012").unwrap();s.lock().unwrap().close_error=true;assert!(b.disconnect("6700 SN1012").is_err());assert!(!b.resources_released());assert!(b.connect("6700 SN1013").is_err());assert!(b.status("6700 SN1012").is_err());s.lock().unwrap().close_error=false;b.disconnect("6700 SN1012").unwrap();assert!(b.resources_released());}
#[test] fn suffix_head_blocks_control_before_getters(){let(mut b,s)=fixture("6722-P");b.connect("6700 SN1012").unwrap();let n=s.lock().unwrap().commands.len();for a in [Action::Remote(true),Action::Wavelength(1060.),Action::Piezo(50.),Action::Tracking(true),Action::Output(true)]{assert_eq!(b.action("6700 SN1012",a,true).unwrap_err().kind,"safety");}assert_eq!(s.lock().unwrap().commands.len(),n);}
#[test] fn fresh_remote_busy_tracking_and_confirmation_gates(){let(mut b,s)=fixture("6722");b.connect("6700 SN1012").unwrap();assert!(b.action("6700 SN1012",Action::Wavelength(1060.),false).is_err());assert!(b.action("6700 SN1012",Action::Wavelength(1060.),true).is_err());s.lock().unwrap().replies.insert("SYST:MCONT?".into(),"REM".into());s.lock().unwrap().replies.insert("OUTP:TRAC?".into(),"0".into());assert!(b.action("6700 SN1012",Action::Wavelength(1060.),true).is_err());s.lock().unwrap().replies.insert("OUTP:TRAC?".into(),"1".into());b.action("6700 SN1012",Action::Wavelength(1060.),true).unwrap();s.lock().unwrap().replies.insert("*OPC?".into(),"0".into());assert!(b.action("6700 SN1012",Action::Output(true),true).is_err());b.action("6700 SN1012",Action::Output(false),true).unwrap();assert!(s.lock().unwrap().commands.iter().any(|(_,c)|c=="OUTP:STAT 0"));}
#[test] fn malformed_numeric_latches_fault_and_never_writes(){let(mut b,s)=fixture("6722");b.connect("6700 SN1012").unwrap();s.lock().unwrap().replies.insert("SOUR:WAVE?".into(),"NaN".into());assert!(b.status("6700 SN1012").is_err());assert!(b.action("6700 SN1012",Action::Output(false),true).is_err());b.disconnect("6700 SN1012").unwrap();assert!(s.lock().unwrap().commands.iter().all(|(_,c)|!c.contains(' ')));}
#[test] fn rejected_write_is_single_attempt_and_faulted(){let(mut b,s)=fixture("6722");b.connect("6700 SN1012").unwrap();s.lock().unwrap().replies.insert("SYST:MCONT?".into(),"REM".into());s.lock().unwrap().replies.insert("OUTP:TRAC 1".into(),"COMMAND NOT VALID".into());assert!(b.action("6700 SN1012",Action::Tracking(true),true).is_err());assert!(b.action("6700 SN1012",Action::Tracking(true),true).is_err());assert_eq!(s.lock().unwrap().commands.iter().filter(|(_,c)|c=="OUTP:TRAC 1").count(),1);}
#[test] fn invalid_key_and_limit_never_open_or_write(){let(mut b,s)=fixture("6722");assert!(b.connect("USB0").is_err());assert_eq!(s.lock().unwrap().opens,0);b.connect("6700 SN1012").unwrap();let n=s.lock().unwrap().commands.len();for v in [f64::NAN,f64::INFINITY,1044.9,1085.1]{assert!(b.action("6700 SN1012",Action::Wavelength(v),true).is_err());}assert_eq!(s.lock().unwrap().commands.len(),n);}
#[test] fn missing_key_releases_temporary_open(){let(mut b,s)=fixture("6722");assert!(b.connect("6700 SN9999").is_err());assert!(b.resources_released());assert_eq!(s.lock().unwrap().closes,1);}
#[test] fn enumeration_opens_and_releases_without_session(){let(mut b,s)=fixture("6722");assert_eq!(b.enumerate().unwrap().len(),2);assert!(b.resources_released());assert_eq!(s.lock().unwrap().opens,1);assert_eq!(s.lock().unwrap().closes,1);}

#[test] fn close_all_failed_release_retains_multiple_sessions_then_releases_once(){let(mut b,s)=fixture("6722");b.connect("6700 SN1012").unwrap();b.connect("6700 SN1013").unwrap();s.lock().unwrap().close_error=true;assert!(b.close_all().is_err());assert!(!b.resources_released());assert!(b.status("6700 SN1012").is_err());assert!(b.status("6700 SN1013").is_err());s.lock().unwrap().close_error=false;b.close_all().unwrap();assert!(b.resources_released());assert_eq!(s.lock().unwrap().closes,2);b.close_all().unwrap();assert_eq!(s.lock().unwrap().closes,2);}
