use yang_lab_tlb::{sdk,rpc,Error,Result};
use std::collections::VecDeque;
struct Packets {sent:Vec<Vec<u8>>,replies:VecDeque<Result<([u8;64],usize)>>}
impl sdk::PacketIo for Packets {fn send(&mut self,_index:i32,buffer:&mut [u8;64],length:u32)->Result<()>{self.sent.push(buffer[..length as usize].to_vec());Ok(())}fn read(&mut self,_index:i32)->Result<([u8;64],usize)>{self.replies.pop_front().expect("finite replies exhausted")}}
fn packet(text:&str)->Result<([u8;64],usize)>{let mut p=[0;64];p[..text.len()].copy_from_slice(text.as_bytes());Ok((p,64))}
fn empty()->Result<([u8;64],usize)>{Err(Error{kind:"read_failure",message:"empty".into()})}
#[test] fn mutable_packet_uses_strlen_and_expanded_keywords(){assert_eq!(sdk::encode("SOUR:WAVE 1060").unwrap(),b"SOURce:WAVElength 1060");assert!(sdk::encode("*IDN?\nOUTP:STAT 1").is_err());assert!(sdk::encode(&"X".repeat(64)).is_err());let mut io=Packets{sent:vec![],replies:VecDeque::from([packet("OK\r\n")])};assert_eq!(sdk::query(&mut io,0,"OUTP:STAT 0").unwrap(),"OK");assert_eq!(io.sent[0],b"OUTPut:STATe 0");}
#[test] fn first_crlf_padding_is_not_an_extra_scalar(){let mut p=[255;64];p[..5].copy_from_slice(b"REM\r\n");assert_eq!(sdk::frame(&p,64).unwrap(),"REM");assert!(sdk::frame(&p,65).is_err());assert!(sdk::frame(b"NaN",3).is_err());assert!(sdk::frame(b"\r\n",2).is_err());assert!(sdk::frame(b"ON\nOFF\r\n",9).is_err());}
#[test] fn getters_retry_once_after_bounded_drain(){let mut io=Packets{sent:vec![],replies:VecDeque::from([empty(),packet("OLD\r\n"),empty(),packet("1060\r\n")])};assert_eq!(sdk::query(&mut io,0,"SENS:WAVE").unwrap(),"1060");assert_eq!(io.sent.len(),2);}
#[test] fn write_failure_and_rejection_never_retry(){for reply in [empty(),packet("COMMAND NOT VALID\r\n")] {let mut io=Packets{sent:vec![],replies:VecDeque::from([reply])};let _=sdk::query(&mut io,0,"OUTP:STAT 1");assert_eq!(io.sent.len(),1);assert!(io.replies.is_empty());}}
#[test] fn sync_input_is_bounded(){let mut io=Packets{sent:vec![],replies:VecDeque::from(vec![packet("OLD\r\n");16])};assert!(sdk::drain(&mut io,0).is_err());assert!(io.replies.is_empty());}
#[test] fn rpc_strict_duplicate_unknown_oversized_and_raw_rejected(){assert!(rpc::parse(br#"{"id":1,"operation":{"method":"resources"}}"#).is_ok());for input in [br#"{"id":1,"id":2,"operation":{"method":"resources"}}"#.as_slice(),br#"{"id":1,"operation":{"method":"resources","raw":"*RST"}}"#,br#"{"id":1,"operation":{"method":"raw","command":"*RST"}}"#,br#"{"id":1,"operation":{"method":"action","key":"6700 SN1","confirm":true,"action":{"name":"output","value":1}}}"#]{assert!(rpc::parse(input).is_err());}assert!(rpc::parse(&vec![b' ';4097]).is_err());}
