import {esc} from './panels.js';import {routeFor} from './routes.js';
export const signature=d=>JSON.stringify([d.modelId,d.profileId,d.name,d.params]);
export function driverCheckReady(d,profile,now=performance.now()) {const c=d.driverCheck;return profile?.access!=='newport'||Boolean(c&&c.modelId===d.modelId&&c.profileId===d.profileId&&c.state==='ready'&&now>=c.issued&&now-c.issued<60000);}
export function controllerChoiceReady(d,now=performance.now()){const s=d.controllerScan;return Boolean(s?.state==='ready'&&(!s.modelId||s.modelId===d.modelId)&&(!s.profileId||s.profileId===d.profileId)&&now>=s.issued&&now-s.issued<60000&&s.controllers.some(c=>c.device_key===d.params?.device_key));}
export function testFormReady(d,model,profile){
 const check=d.driverCheck,scan=d.controllerScan;
 const prerequisite=profile?.access!=='newport'||check?.state==='ready'&&check.modelId===d.modelId&&check.profileId===d.profileId;
 return Boolean(profile&&prerequisite&&(model?.id!=='tlb6700'||scan?.state==='ready'&&scan.controllers.some(c=>c.device_key===d.params?.device_key)));
}
export function canSave(d,now=performance.now()){return Boolean(d.record&&d.proof?.proof_id&&d.proof.revision===d.record.revision&&d.proof.signature===signature(d)&&now>=d.proof.issued&&now-d.proof.issued<60000);}
export function instrumentTarget(record,setups=[]){const owner=setups.find(s=>s.members.includes(record.device_id));return owner?{kind:'setup',id:owner.setup_id}:{kind:'device',id:record.device_id};}
const options=(items,value)=>items.map(([id,label])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
export function renderDriverStatus(inventory,available=true){
  const status=inventory?.newport,ready=status?.sdk?.state==='ready'&&!inventory?.errors?.newport&&!status.devices?.some(d=>d.driver_state!=='ready');
  const missing=status?.sdk?.state==='missing'||status?.devices?.some(d=>d.driver_state==='missing');
  const state=inventory?.checking?'Checking…':ready?'Installed':missing?'Not installed':status||inventory?.errors?.newport?'Could not check':'Not checked';
  return `<section class="card settings-section"><div class="card-head"><h2>Drivers</h2><button class="btn" data-ui="check-drivers" ${inventory?.checking||!available?'disabled':''}>Refresh</button></div><div class="card-body"><div class="device-row"><strong>Newport USB</strong><span ${missing||state==='Could not check'?'class="alert"':''}>${state}</span>${missing?`<button class="btn" data-ui="install-driver" ${available?'':'disabled'}>Install driver</button>`:''}</div>${inventory?.errors?.newport?`<p class="alert">${esc(inventory.errors.newport)}</p>`:''}</div></section>`;
}
export function renderCheckPolicy(d,catalog={models:[]}) {const id=esc(d.device_id),policy=d.check_policy||{};
 return `<details id="checks-${id}" class="online-checks"><summary>Refresh</summary><label>Refresh interval (seconds)<input class="control" type="number" min="10" step="1" id="check-interval-${id}" value="${policy.interval_s||30}"></label><button class="btn" data-ui="save-checks" data-device="${id}">Save interval</button><button class="btn" data-ui="refresh-device" data-device="${id}">Refresh now</button></details>`;
}
export function renderAddWizard(d={},catalog={categories:[],models:[]}){
  const model=catalog.models.find(m=>m.id===d.modelId),profile=model?.profiles.find(p=>p.id===d.profileId),category=d.category||model?.category||catalog.categories[0];
  return `<div class="wizard-backdrop" data-wizard-backdrop="true"></div><div class="card wizard" role="dialog" aria-modal="true" aria-label="Add New Instrument"><div class="card-head"><h2>Add New Instrument</h2><button class="btn" data-ui="cancel-wizard" ${d.busy||d.installing?'disabled':''}>Cancel</button></div><div class="card-body"><fieldset ${d.busy||d.installing?'disabled':''}>
    <label>Category<select class="control" data-draft="category">${options(catalog.categories.map(c=>[c,c]),category)}</select></label>
    <label>Manufacturer and model<select class="control" data-draft="modelId"><option value="">Select model</option>${options(catalog.models.filter(m=>m.category===category).map(m=>[m.id,`${m.manufacturer} · ${m.name}`]),d.modelId)}</select></label>
    ${!model?(d.modelId?'<p class="alert">Driver required for this model.</p>':''):`<label>Name<input class="control" data-draft="name" value="${esc(d.name||model.name)}" maxlength="128"></label>
    <label>Connection<select class="control" data-draft="profileId">${options(model.profiles.map(p=>[p.id,`${p.interfaces.join(' / ')} · ${p.access.toUpperCase()}`]),d.profileId)}</select></label>
    ${profile?Object.entries(profile.fields).map(([key,f])=>key==='device_key'&&model.id==='tlb6700'?`<label>Controller serial number<select class="control" data-param="device_key" data-managed="true" ${d.controllerScan?.state==='ready'?'':'disabled'}><option value="">${d.controllerScan?.state==='checking'?'Scanning…':'Select controller'}</option>${options((d.controllerScan?.controllers||[]).map(c=>[c.device_key,c.serial]),d.params?.device_key)}</select></label><button class="btn" data-ui="scan-controllers" ${d.busy||d.controllerScan?.state==='checking'?'disabled':''}>Refresh devices</button>${d.controllerScan?.state==='failed'?`<p class="alert">Scan failed: ${esc(d.controllerScan.message)}</p>`:d.controllerScan?.state==='ready'&&!d.controllerScan.controllers.length?'<p class="alert">No TLB-6700 detected. Check USB connection, then refresh.</p>':''}`:`<label>${esc(key.replaceAll('_',' '))}${f.choices?`<select class="control" data-param="${esc(key)}">${options(f.choices.map(v=>[String(v),String(v)]),String(d.params?.[key]??f.default))}</select>`:`<input class="control" data-param="${esc(key)}" type="${['number','integer'].includes(f.kind)?'number':'text'}" value="${esc(d.params?.[key]??f.default??'')}" ${f.minimum!==undefined?`min="${f.minimum}"`:''} ${f.maximum!==undefined?`max="${f.maximum}"`:''} step="${f.kind==='integer'?'1':'any'}" ${f.required?'required':''}>`}</label>`).join(''):''}
    ${profile?.access==='newport'&&d.driverCheck?.state==='missing'?`<p class="alert">Newport USB driver or SDK is missing. <button class="btn" data-ui="install-draft-driver" ${d.installing?'disabled':''}>${d.installing?'Installing…':'Install driver'}</button></p>`:profile?.access==='newport'&&d.driverCheck?.state==='unavailable'?`<p class="alert">${esc(d.driverCheck.message)} <button class="btn" data-ui="check-draft-drivers">Retry check</button></p>`:''}
    ${d.installError?`<p class="alert">${esc(d.installError)}</p>`:''}
    ${profile?.probe_mode==='supervised'?`<p class="warning">Prepare session: ${esc(model.connect_effects?.join(', '))}. On close: ${esc(model.close_effects?.join(', '))}.</p>`:''}
    ${profile?.open_effects.length?`<p class="warning">Open effects: ${esc(profile.open_effects.join(', '))}</p>`:''}
    <div class="form-actions">${profile?.probe_mode==='supervised'?'<button class="btn warn" data-ui="prepare-draft">Prepare supervised session</button>':''}<button class="btn primary" data-ui="test-draft" ${d.busy||d.installing||!testFormReady(d,model,profile)?'disabled':''}>Test Connection</button>
    <button class="btn primary" data-ui="save-draft" ${canSave(d)&&!d.busy?'':'disabled'}>Add &amp; Save</button></div>`}
    ${d.proof?.proof_id&&!canSave(d)?'<p class="alert">Connection check expired. Test again.</p>':''}
    ${d.releaseError?'<button class="btn danger" data-ui="safe-stop-draft">Retry connection release</button><p class="hint">Connection release failed. Retry release before continuing.</p>':''}
    ${d.message?`<p role="status">${esc(d.message)}</p>`:''}</fieldset></div></div>`;
}
export const setupChoices=r=>r.devices.filter(d=>d.model_id==='mdt693b'&&['2110148249-10','160721175410'].includes(d.expected_identity?.serial)&&!r.setups.some(s=>s.members.includes(d.device_id)));
export function renderDeviceSetup(host,catalog={models:[]},editor={}){const r=host.registry||{devices:[],setups:[],drafts:[]};const html=`<div class="page-header"><div><div class="eyebrow">LOCAL / CONFIGURATION</div><h1>Device setup</h1></div><button class="btn primary" data-ui="add-new">＋ Add New</button></div>
  <div class="device-list">${r.devices.map(d=>`<article class="card device-row"><div>${editor.rename===d.device_id?`<label>Instrument name<input class="control" id="rename-name" value="${esc(d.name)}" maxlength="128"></label><button class="btn primary" data-ui="save-rename" data-device="${d.device_id}">Save name</button><button class="btn" data-ui="cancel-editor">Cancel</button>`:`<h2>${esc(d.name)}</h2>`}<small>${esc(catalog.models.find(m=>m.id===d.model_id)?.name||d.model_id)} · S/N ${esc(d.expected_identity?.serial||d.expected_identity?.transport_serial||'Unknown')}</small>${renderCheckPolicy(d,catalog)}</div><a class="btn" href="${routeFor(host.host_id,instrumentTarget(d,r.setups))}">Open</a><button class="btn" data-ui="rename" data-device="${d.device_id}">Rename</button><button class="btn warn" data-ui="retire" data-device="${d.device_id}">Remove</button></article>`).join('')||'<div class="empty-panel">No instruments configured.</div>'}</div>
  ${r.drafts.filter(d=>d.status!=='Cancelled').map(d=>`<article class="card device-row"><span>${esc(d.name)} · ${esc(d.status)}</span><button class="btn" data-ui="open-draft" data-device="${d.device_id}">Review draft</button><button class="btn warn" data-ui="cancel-draft" data-device="${d.device_id}">Cancel draft</button></article>`).join('')}
  ${r.setups.length||setupChoices(r).length?`<div class="section-title"><h2>Fiber coupling</h2><button class="btn" data-ui="add-setup">Add setup</button></div>${r.setups.map(s=>`<article class="card device-row"><span>${esc(s.name)} · ${s.members.length} controller(s)</span><a class="btn" href="${routeFor(host.host_id,{kind:'setup',id:s.setup_id})}">Open</a><button class="btn warn" data-ui="retire-setup" data-setup="${s.setup_id}">Remove setup</button></article>`).join('')}`:''}${editor.addSetup?`<section class="card"><div class="card-body"><label>Setup name<input class="control" id="setup-name" value="Fiber coupling" maxlength="128"></label>${setupChoices(r).map(d=>`<label><input type="checkbox" id="setup-member-${d.device_id}"> ${esc(d.name)} · ${esc(d.expected_identity.serial)}</label>`).join('')}<button class="btn primary" data-ui="save-setup">Save setup</button><button class="btn" data-ui="cancel-editor">Cancel</button></div></section>`:''}`;return host.connected?html:html.replaceAll('<button ','<button disabled ');}
export function renderSettings(host,preferences){return `<h1>Settings</h1>
  <section class="card settings-section"><div class="card-head"><h2>Local Host</h2><span class="badge">${host?.connected?'ONLINE':'OFFLINE'}</span></div><div class="card-body"><label>Host name<input class="control" id="host-name" value="${esc(host?.registry?.settings?.host_name||'Local computer')}" ${host?.connected?'':'disabled'}></label>
  <label>Recording folder<input class="control" id="host-data-root" readonly value="${esc(host?.registry?.settings?.data_root||host?.archive?.active_root||'')}"></label><button class="btn" data-ui="choose-data-root" ${host?.connected?'':'disabled'}>Choose folder</button>
  <details id="host-advanced"><summary>Advanced</summary><label>Anaconda VISA Python<input class="control" id="host-python" placeholder="VISA/python.exe" value="${esc(preferences?.pythonPath||host?.registry?.settings?.python_path||'')}"></label>
  <p class="hint">Python and recording folder changes apply after restarting Host.</p><p class="warning">Stop Host releases instruments: voltage zero, gain current off before TEC, piezo holds.</p><div class="form-actions"><button class="btn" data-ui="connect-host" ${host?.connected?'disabled':''}>Reconnect</button><button class="btn" data-ui="start-host" ${host?.connected?'disabled':''}>Start Host</button><button class="btn warn" data-ui="stop-host" ${host?.connected?'':'disabled'}>Stop Host</button><button class="btn" data-ui="disconnect-host" ${host?.connected?'':'disabled'}>Disconnect GUI</button></div></details>
  <button class="btn primary" data-ui="save-host">Save settings</button></div></section>${renderDriverStatus(host?.driverInventory,host?.connected)}`;}
export function renderSetup(key,store){const state=store.get(key);return `<h1>Fiber coupling</h1><p>Laboratory coordinates: +X right · +Y away from operator · +Z up</p><p class="warning">Session-only open-loop estimate. Baseline adoption requires explicit operator confirmation.</p><pre>${esc(JSON.stringify(state?.device??{},null,2))}</pre>`;}
