import {esc} from './panels.js';import {routeFor} from './routes.js';
import {renderConnections} from './connections.js';
export const signature=d=>JSON.stringify([d.modelId,d.profileId,d.name,d.params]);
export function canSave(d,now=performance.now()){return Boolean(d.record&&d.proof?.proof_id&&d.proof.revision===d.record.revision&&d.proof.signature===signature(d)&&now>=d.proof.issued&&now-d.proof.issued<60000);}
export function instrumentTarget(record,setups=[]){const owner=setups.find(s=>s.members.includes(record.device_id));return owner?{kind:'setup',id:owner.setup_id}:{kind:'device',id:record.device_id};}
const options=(items,value)=>items.map(([id,label])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
export function renderCheckPolicy(d,catalog={models:[]}) {const profile=catalog.models.find(m=>m.id===d.model_id)?.profiles.find(p=>p.id===d.profile_id),allowed=profile?.probe_mode==='readonly'&&profile.automatic_probe&&!profile.open_effects.length;
  const id=esc(d.device_id),policy=d.check_policy||{};return `<details id="checks-${id}" class="online-checks"><summary>Online checks</summary><label><input type="checkbox" id="check-enumeration-${id}" ${policy.enumeration?'checked':''}> Enumerate resources</label><label><input type="checkbox" id="check-readonly-${id}" ${allowed?'':'disabled'} ${allowed&&policy.readonly?'checked':''}> Read-only identity probe</label><label>Interval (seconds)<input class="control" type="number" min="10" step="1" id="check-interval-${id}" value="${policy.interval_s||30}"></label><button class="btn" data-ui="save-checks" data-device="${id}">Save check policy</button>${allowed?'':'<p class="hint">Automatic active checks are unavailable for this profile.</p>'}</details>`;
}
export function renderAddWizard(d={},catalog={categories:[],models:[]}){
  const model=catalog.models.find(m=>m.id===d.modelId),profile=model?.profiles.find(p=>p.id===d.profileId),category=d.category||model?.category||catalog.categories[0];
  return `<div class="card wizard"><div class="card-head"><h2>Add New Instrument</h2><button class="btn" data-ui="cancel-wizard">Cancel</button></div><div class="card-body">
    <label>Category<select class="control" data-draft="category">${options(catalog.categories.map(c=>[c,c]),category)}</select></label>
    <label>Manufacturer and model<select class="control" data-draft="modelId"><option value="">Select model</option>${options(catalog.models.filter(m=>m.category===category).map(m=>[m.id,`${m.manufacturer} · ${m.name}`]),d.modelId)}</select></label>
    ${!model?'<p class="hint">Driver required for unsupported models. No device will be registered.</p>':`<label>Name<input class="control" data-draft="name" value="${esc(d.name||model.name)}" maxlength="128"></label>
    <label>Connection<select class="control" data-draft="profileId">${options(model.profiles.map(p=>[p.id,`${p.interfaces.join(' / ')} · ${p.access.toUpperCase()}`]),d.profileId)}</select></label>
    ${profile?Object.entries(profile.fields).map(([key,f])=>`<label>${esc(key.replaceAll('_',' '))}${f.choices?`<select class="control" data-param="${esc(key)}">${options(f.choices.map(v=>[String(v),String(v)]),String(d.params?.[key]??f.default))}</select>`:`<input class="control" data-param="${esc(key)}" type="${['number','integer'].includes(f.kind)?'number':'text'}" value="${esc(d.params?.[key]??f.default??'')}" ${f.minimum!==undefined?`min="${f.minimum}"`:''} ${f.maximum!==undefined?`max="${f.maximum}"`:''} step="${f.kind==='integer'?'1':'any'}" ${f.required?'required':''}>`}</label>`).join(''):''}
    <p class="hint">${profile?.probe_mode==='supervised'?'Manual verification required. Prepare a separately confirmed session before testing.':'Testing reads identity and closes the temporary session.'}</p>
    ${profile?.open_effects.length?`<p class="warning">Open effects: ${esc(profile.open_effects.join(', '))}</p>`:''}
    <div class="form-actions">${profile?.probe_mode==='supervised'?'<button class="btn warn" data-ui="prepare-draft">Prepare supervised session</button>':''}<button class="btn primary" data-ui="test-draft" ${d.busy?'disabled':''}>Test Connection</button>
    <button class="btn primary" data-ui="save-draft" ${canSave(d)&&!d.busy?'':'disabled'}>Add and Save</button></div>`}
    ${d.record?'<button class="btn danger" data-ui="safe-stop-draft">Safe stop / release draft session</button><p class="hint">To change a tested connection, cancel this draft after confirmed release, then create a new one.</p>':''}
    ${d.message?`<p role="status">${esc(d.message)}</p>`:''}</div></div>`;
}
export function renderDeviceSetup(host,catalog={models:[]}){const r=host.registry||{devices:[],setups:[],drafts:[]};const html=`<div class="page-header"><div><div class="eyebrow">LOCAL / CONFIGURATION</div><h1>Device setup</h1></div><button class="btn primary" data-ui="add-new">＋ Add New</button></div>
  <div class="device-list">${r.devices.map(d=>`<article class="card device-row"><div><h2>${esc(d.name)}</h2><small>${esc(d.model_id)} · ${esc(d.params.resource||d.params.port)} · ${esc(d.identity_strength)}</small>${renderCheckPolicy(d,catalog)}</div><a class="btn" href="${routeFor(host.host_id,instrumentTarget(d,r.setups))}">Open</a><button class="btn" data-ui="rename" data-device="${d.device_id}">Rename</button><button class="btn warn" data-ui="retire" data-device="${d.device_id}">Remove</button></article>`).join('')||'<div class="empty-panel">No instruments configured.</div>'}</div>
  ${r.drafts.filter(d=>d.status!=='Cancelled').map(d=>`<article class="card device-row"><span>${esc(d.name)} · ${esc(d.status)}</span><button class="btn" data-ui="open-draft" data-device="${d.device_id}">Review draft</button><button class="btn warn" data-ui="cancel-draft" data-device="${d.device_id}">Cancel draft</button></article>`).join('')}
  <div class="section-title"><h2>Fiber setups</h2><button class="btn" data-ui="add-setup">Add setup</button></div>${r.setups.map(s=>`<article class="card device-row"><span>${esc(s.name)} · ${s.members.length} controller(s)</span><a class="btn" href="${routeFor(host.host_id,{kind:'setup',id:s.setup_id})}">Open</a><button class="btn warn" data-ui="retire-setup" data-setup="${s.setup_id}">Remove setup</button></article>`).join('')}`;return host.connected?html:html.replaceAll('<button ','<button disabled ');}
export function renderSettings(host,preferences,remote={peers:[],owner:null},connections){return `<h1>Settings</h1>
  <section class="card settings-section"><div class="card-head"><h2>General</h2></div><div class="card-body"><p>Yang LAB INSTRUMENT CONSOLE · English</p><p class="hint">The app connects to the local Host automatically.</p></div></section>
  <section class="card settings-section"><div class="card-head"><h2>Local Host</h2><span class="badge">${host?.connected?'ONLINE':'OFFLINE'}</span></div><div class="card-body"><label>Host name<input class="control" id="host-name" value="${esc(host?.registry?.settings?.host_name||'Local computer')}" ${host?.connected?'':'disabled'}></label>
  <label>Recording folder<input class="control" id="host-data-root" readonly value="${esc(host?.registry?.settings?.data_root||host?.archive?.active_root||'')}"></label><button class="btn" data-ui="choose-data-root" ${host?.connected?'':'disabled'}>Choose folder</button>
  <p class="hint">Recording folder changes apply after a safe Host restart. Instrument connections and outputs are not restored.</p><div class="form-actions"><button class="btn primary" data-ui="save-host">Save settings</button><button class="btn" data-ui="connect-host" ${host?.connected?'disabled':''}>Reconnect</button><button class="btn" data-ui="start-host" ${host?.connected?'disabled':''}>Start Host</button><button class="btn warn" data-ui="stop-host" ${host?.connected?'':'disabled'}>Stop Host</button><button class="btn" data-ui="disconnect-host" ${host?.connected?'':'disabled'}>Disconnect GUI</button></div></div></section>
  ${renderConnections({...remote,localConnected:host?.connected},connections)}`;}
export function renderSetup(key,store){const state=store.get(key);return `<h1>Fiber coupling</h1><p>Laboratory coordinates: +X right · +Y away from operator · +Z up</p><p class="warning">Session-only open-loop estimate. Baseline adoption requires explicit operator confirmation.</p><pre>${esc(JSON.stringify(state?.device??{},null,2))}</pre>`;}
